  apiVersion:	v1
  kind:	Service
  metadata:	
    name:	dep-service
    namespace: gitops-demo
  spec:
    type: ClusterIP
    selector:
      app: niginx
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 80
