apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ranagit-ux/argocdnew.git
    targetRevision: main
    path: environments/dev/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-namespace-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
