apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ranagit-ux/argocdnew.git
        revision: main
        directories:
          - path: environments/*/frontend
  template:
    metadata:
      name: 'frontend-{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ranagit-ux/argocdnew.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd-namespace-{{path[1]}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true